### PR TITLE
add IsDir to targetPathExists check

### PR DESCRIPTION
**Pull request by mwhooker**

### CODE REVIEW

**Comment by Tonnu** [comment]
+1

**Comment by hatchan** [comment]
:+1:

**Comment by flenter** [comment]
lgtm.

minor comment: if the path points to a file, this function returns false and we display the message: 

> cowardly refusing to make destination directory
https://github.com/wercker/mhook/blob/isdir/mhook.go#L101

Which, to me, suggests that nothing exists there. But that's not true.

**Comment by mwhooker** [comment]
Thanks for the comment @flenter. I reworded the message and changed the function name

**Pull request merged**
