### PR TITLE
progress bar

### PR DESCRIPTION
**Pull request by mwhooker**
```
~/dev/mhook (master ✘)✹✭ ᐅ ./mhook --bucket wercker-development --project kiddie-pool --branch master --commit latest linux_amd64/kiddie-pool ./kp                                             (gliding)
9.87 MB / 9.93 MB [===========================================================================================================================================================================] 99.46 % 0
```

### CODE REVIEW

**Comment by termie** [comment]
lgtm

**Comment by termie** [comment]
can we turn off the bar when we aren't using it locally?

**Comment by termie** [comment]
or did you just fuck all our logs

**Comment by mwhooker** [comment]
Probably just fucked all the logs. decided better to commit now and fix later if it’s an issue

-- 
Matthew Hooker

On April 20, 2015 at 3:00:02 PM, Andy Smith (notifications@github.com) wrote:

or did you just fuck all our logs

**Pull request merged**
